import test from 'node:test';
import assert from 'node:assert/strict';
import * as T from 'three';
import { freshTown, parseTown, TownStore } from '../../src/town/store';
import { farmChains, tickFarm, roadRoute, farmDuration, bakeryMaterialLabel } from '../../src/town/farming';
import { unlocked, evaluate, makeBuilding, cells, canPlace } from '../../src/town/world';
import { keyboardIntent, keyboardPan } from '../../src/town/keyboard-input';
import { PedestrianTraffic, samplePatrol } from '../../src/town/pedestrians';
import { ResidentLife, homeForBuilding } from '../../src/town/resident-life';
import { buildingModel, packModel } from '../../src/town/models';
import { installLocalStorage } from '../helpers';

function fixture(){const s=freshTown('demo');s.town.roads.push('6,17','12,16','13,16','14,16','15,16','16,16','16,17');s.town.buildings.push(makeBuilding('field','wheatfield',12,14),makeBuilding('mill','mill',15,18,2));return s;}
test('starting district gains 50 percent land and keeps a meaningful second land unlock',()=>{const s=freshTown('demo');let land=0;for(let x=0;x<24;x++)for(let z=13;z<24;z++)if(unlocked(s,s.town,x,z))land++;assert.equal(land,198);assert.ok(unlocked(s,s.town,17,23));assert.equal(unlocked(s,s.town,18,23),false);s.chapterStars[1]=1;assert.ok(unlocked(s,s.town,23,23));assert.equal(unlocked(s,s.town,17,10),false);});
test('Q/E rotates the preview once while WASD supports normalized diagonal movement',()=>{assert.equal(keyboardIntent('q',true),'turn-left');assert.equal(keyboardIntent('E',true),'turn-right');assert.equal(keyboardIntent('e',true,true),null);assert.equal(keyboardIntent('q',false,true),'camera-turn');assert.equal(keyboardIntent('r',true),'turn-right');assert.equal(keyboardIntent('w',true),'pan');const diagonal=keyboardPan(new Set(['w','d']));assert.ok(Math.abs(Math.hypot(diagonal.x,diagonal.y)-1)<1e-9);assert.deepEqual(keyboardPan(new Set(['a','d','w','s'])),{x:0,y:0});});
test('wheat flows through reachable roads into flour and four loaves, with no coin reward',()=>{const s=fixture(),e=evaluate(s.town),chains=farmChains(s.town,e,s.farm);assert.equal(chains[0].problem,'');for(const b of s.town.buildings)assert.equal(canPlace(s,s.town,b),null);const phases=new Set<string>();for(let i=0;i<1400&&s.farm.batches===0;i++){tickFarm(chains,s.farm,.1,false,'spring');phases.add(s.farm.runs.field.phase);}assert.equal(s.farm.batches,1);assert.equal(s.farm.bread,4);assert.equal(s.farm.wheat,0);assert.equal(s.farm.flour,1);assert.equal(s.coins,0);for(const phase of ['sowing','growing','harvesting','to-mill','milling','to-bakery','baking'])assert.ok(phases.has(phase));assert.ok(farmDuration(chains[0],'growing','summer')<farmDuration(chains[0],'growing','winter'));assert.ok(parseTown(JSON.stringify(s),'demo'));});
test('road interruption, storage, absence of a worker and night all pause production without duplication',()=>{const s=fixture(),e=evaluate(s.town),chains=farmChains(s.town,e,s.farm);tickFarm(chains,s.farm,1,false,'spring');const before=JSON.stringify(s.farm);tickFarm(chains,s.farm,1,true,'summer');assert.equal(JSON.stringify(s.farm),before);tickFarm(chains,s.farm,1,false,'spring',new Set());assert.equal(JSON.stringify(s.farm),before);s.town.roads=s.town.roads.filter(k=>k!=='16,17');const broken=farmChains(s.town,evaluate(s.town),s.farm);assert.ok(broken[0].problem);tickFarm(broken,s.farm,1,false,'spring');assert.equal(JSON.stringify(s.farm),before);s.town.roads.push('16,17');tickFarm(farmChains(s.town,evaluate(s.town),s.farm),s.farm,1,false,'spring');assert.equal(s.farm.runs.field.elapsed,2);s.town.buildings.find(b=>b.id==='field')!.placed=false;assert.equal(farmChains(s.town,evaluate(s.town),s.farm).length,0);});
test('transport follows a road detour and cannot cut through occupied squares',()=>{const roads=new Set(['0,0','1,0','2,0','2,1','2,2','1,2','0,2']);const path=roadRoute(roads,{x:.5,z:.5},{x:.5,z:2.5});assert.equal(path.length,7);assert.ok(path.every(p=>roads.has(`${Math.floor(p.x)},${Math.floor(p.z)}`)));roads.delete('2,1');assert.deepEqual(roadRoute(roads,{x:.5,z:.5},{x:.5,z:2.5}),[]);});
test('older town saves acquire empty farm and music settings, and malformed new state is rejected',()=>{const old:any=freshTown('demo');delete old.farm;delete old.settings.music;delete old.settings.musicVolume;const s=parseTown(JSON.stringify(old),'demo')!;assert.ok(s);assert.equal(s.farm.bread,0);assert.equal(s.settings.music,true);assert.equal(s.settings.musicVolume,.28);s.settings.musicVolume=-1;assert.equal(parseTown(JSON.stringify(s),'demo'),null);s.settings.musicVolume=.4;s.farm.wheat=-1;assert.equal(parseTown(JSON.stringify(s),'demo'),null);});
test('farm purchases are permanent, charged once, and reload in separate town inventory',()=>{installLocalStorage();const store=new TownStore('demo');store.syncDemo();for(const [kind,x,z]of [['wheatfield',12,14],['mill',15,18]] as const){const coins=store.state.coins;assert.equal(store.place(kind,x,z,0),null);const b=store.board.buildings.at(-1)!;assert.equal(store.state.coins,coins-(kind==='mill'?32:6));assert.equal(store.stash(b.id),true);assert.equal(store.place(kind,x,z,0,b.id),null);assert.equal(store.state.coins,coins-(kind==='mill'?32:6));}const restored=new TownStore('demo');assert.equal(restored.board.buildings.filter(b=>['wheatfield','mill'].includes(b.kind)).length,2);restored.setMode('live');assert.equal(restored.state.farm.bread,0);});
test('crop and mill fan articulation survive packing and rotation without invalid footprint occupancy',()=>{for(const kind of ['wheatfield','mill'] as const){const model=packModel(buildingModel(kind));assert.ok(model.getObjectByName(kind==='mill'?'mill-fan':'crop-patch')?.children.length);const bb=new T.Box3().setFromObject(model);assert.ok(bb.max.y<(kind==='mill'?3.9:.9));for(let r=0;r<4;r++){const b=makeBuilding('f',kind,12,14,r);assert.equal(cells(b).length,kind==='mill'?9:6);}}});
test('road changes retain actor identities, positions, gait and sleep state with bounded rejoining',()=>{const s=fixture(),roads=evaluate(s.town).connectedRoads,traffic=new PedestrianTraffic(roads,8),homes=s.town.buildings.filter(b=>b.kind==='house').map(homeForBuilding),life=new ResidentLife(traffic,homes);for(let i=0;i<120;i++)life.update(1/60,false);const people=[...traffic.people],positions=people.map(p=>({x:p.x,z:p.z,total:p.totalTravelled,phase:p.phase})),residentRefs=[...life.residents];roads.add('17,16');traffic.retarget(roads);life.retarget(homes,[]);people.forEach((p,i)=>{assert.equal(traffic.people[i],p);assert.equal(life.residents[i],residentRefs[i]);assert.equal(p.x,positions[i].x);assert.equal(p.z,positions[i].z);assert.equal(p.phase,positions[i].phase);assert.equal(p.totalTravelled,positions[i].total);});for(let frame=0;frame<1200;frame++){const before=people.map(p=>({x:p.x,z:p.z}));life.update(1/60,false);people.forEach((p,i)=>assert.ok(Math.hypot(p.x-before[i].x,p.z-before[i].z)<.025,'no teleport while joining changed pavement'));}const sleeping=new ResidentLife(new PedestrianTraffic(roads,8),homes,true);sleeping.traffic.retarget(new Set(roads));sleeping.retarget(homes,[]);assert.ok(sleeping.residents.every(r=>r.mode==='sleeping'&&!r.visible));traffic.retarget(new Set());traffic.update(.1);assert.ok(traffic.people.every(p=>p.travelled===0));});
test('a working villager reaches the field on foot, completes a batch, then goes home at night',()=>{const s=fixture(),e=evaluate(s.town),traffic=new PedestrianTraffic(e.connectedRoads,8),homes=s.town.buildings.filter(b=>b.kind==='house').map(homeForBuilding),life=new ResidentLife(traffic,homes),chains=farmChains(s.town,e,s.farm);life.setBuildings(s.town.buildings);life.setPlaces([],e.connectedRoads);for(let frame=0;frame<60*250;frame++){const ready=new Set<string>();for(const [i,job]of life.jobs){const p=traffic.people[i];if(!life.residents[i].path.length&&Math.hypot(p.x-job.target.x,p.z-job.target.z)<.15)ready.add(job.fieldId);}const jobs=tickFarm(chains,s.farm,1/60,false,'spring',ready);life.assignJobs(jobs,(from,to)=>{const start=[...e.connectedRoads].map(k=>{const [x,z]=k.split(',').map(Number);return{x:x+.5,z:z+.5};}).sort((a,b)=>Math.hypot(a.x-from.x,a.z-from.z)-Math.hypot(b.x-from.x,b.z-from.z))[0];return roadRoute(e.connectedRoads,start,to);});const before=traffic.people.map(p=>({x:p.x,z:p.z}));life.update(1/60,false);traffic.people.forEach((p,i)=>assert.ok(Math.hypot(p.x-before[i].x,p.z-before[i].z)<.02));}assert.ok(s.farm.bread>=4,JSON.stringify({farm:s.farm,jobs:[...life.jobs],people:traffic.people.slice(0,3),r:life.residents[0]}));assert.equal(life.residents[0].mode,'working');life.assignJobs([],()=>[]);for(let i=0;i<60*250;i++)life.update(1/60,true);assert.ok(life.residents.every(r=>r.mode==='sleeping'));});
test('farm-only checkpoints merge the latest harvest while retaining another window\'s pending building action',()=>{installLocalStorage();const first=new TownStore('demo');first.syncDemo();const second=new TownStore('demo');first.state.farm.activeSeconds=120;first.state.farm.bread=4;first.state.farm.batches=1;first.commit(false);assert.equal(second.place('house',12,21,0),null);assert.equal(second.conflict,false);assert.equal(second.state.farm.bread,4);assert.equal(second.state.farm.activeSeconds,120);assert.ok(new TownStore('demo').board.buildings.some(b=>b.kind==='house'&&b.x===12));});
test('a farmer leaving work reserves a free pavement slot instead of blocking the bedtime queue',()=>{const s=fixture(),e=evaluate(s.town),traffic=new PedestrianTraffic(e.connectedRoads,8),homes=s.town.buildings.filter(b=>b.kind==='house').map(homeForBuilding),life=new ResidentLife(traffic,homes);const p=traffic.people[0];p.active=false;Object.assign(p,samplePatrol(traffic.track,traffic.people[1].distance+.15));life.residents[0].mode='working';life.assignJobs([],()=>[]);for(let frame=0;frame<60*300;frame++)life.update(1/60,true);assert.ok(life.residents.every(r=>r.mode==='sleeping'),JSON.stringify(life.residents.map(r=>r.mode)));});

test('flour in transit names its destination bakery and does not satisfy another shop or a broken chain',()=>{const s=fixture(),chains=farmChains(s.town,evaluate(s.town),s.farm);tickFarm(chains,s.farm,0,false,'spring');s.farm.flour=2;s.farm.runs.field.phase='to-bakery';assert.equal(bakeryMaterialLabel('bakery-1',chains,s.farm,false),'面粉正在送来');assert.equal(bakeryMaterialLabel('other-bakery',chains,s.farm,false),'缺少原材料：面粉');s.farm.runs.field.phase='baking';assert.equal(bakeryMaterialLabel('bakery-1',chains,s.farm,false),'烘焙中 · 0% · 烘焙还需 3 秒');chains[0].problem='麦田断路';assert.equal(bakeryMaterialLabel('bakery-1',chains,s.farm,false),'缺少原材料：面粉');assert.equal(bakeryMaterialLabel('bakery-1',chains,s.farm,true),'夜间休息中');});
