/*
 * measured.ts — GENERATED by scripts/measure-assets.mjs. Do not edit by hand;
 * re-run the script if the art assets change.
 *
 * Anchor points measured from the generated art with sharp, so screens place
 * dynamic content exactly where the art expects it.
 */

/** Per-cell centers of the P1C achievement display (5 shelves x 10 slots),
 * measured from display-50-v1.png. Rarity rails sit separately at x=0.13. */
const DISPLAY_X = [0.2287, 0.2999, 0.3711, 0.4423, 0.5135, 0.5851, 0.6558, 0.727, 0.7982, 0.8694];
const DISPLAY_Y = [0.2144, 0.3554, 0.4978, 0.6401, 0.7843];
export const DISPLAY_SLOTS: { x: number; y: number }[][] = DISPLAY_Y.map((y) =>
  DISPLAY_X.map((x) => ({ x, y })),
);

/** Center of the five separate rarity-name rails. */
export const DISPLAY_RARITY_RAILS: { x: number; y: number }[] = DISPLAY_Y.map((y) => ({ x: 0.1563, y }));

/** Per-cell centers of the home prize wall (5 shelves x 4 slots), as fractions
 * of the drawn image box. */
export const PRIZE_WALL_SLOTS: { x: number; y: number }[][] = [[{"x":0.24,"y":0.211},{"x":0.4125,"y":0.211},{"x":0.5775,"y":0.211},{"x":0.7425,"y":0.211}],[{"x":0.24,"y":0.338},{"x":0.4125,"y":0.338},{"x":0.5775,"y":0.338},{"x":0.7425,"y":0.338}],[{"x":0.24,"y":0.455},{"x":0.4125,"y":0.455},{"x":0.5775,"y":0.455},{"x":0.7425,"y":0.455}],[{"x":0.24,"y":0.568},{"x":0.4125,"y":0.568},{"x":0.5775,"y":0.568},{"x":0.7425,"y":0.568}],[{"x":0.24,"y":0.692},{"x":0.4125,"y":0.692},{"x":0.5775,"y":0.692},{"x":0.7425,"y":0.692}]];

/** The home room background's visual center line (lamp + wall-gap blend),
 * as a fraction of image width. */
export const ROOM_CENTER_X = 0.5167;
