/*
 * measured.ts — GENERATED by scripts/measure-assets.mjs. Do not edit by hand;
 * re-run the script if the art assets change.
 *
 * Anchor points measured from the generated art with sharp, so screens place
 * dynamic content exactly where the art expects it.
 */

/** Per-cell centers of the achievement display cabinet (5 shelves x 9 slots),
 * as fractions of the drawn image box. The AI-drawn grid is not uniform. */
export const DISPLAY_SLOTS: { x: number; y: number }[][] = [[{"x":0.1472,"y":0.2156},{"x":0.2408,"y":0.2156},{"x":0.3321,"y":0.2156},{"x":0.4225,"y":0.2156},{"x":0.5146,"y":0.2156},{"x":0.6043,"y":0.2156},{"x":0.694,"y":0.2156},{"x":0.7814,"y":0.2156},{"x":0.8635,"y":0.2156}],[{"x":0.1488,"y":0.3657},{"x":0.2408,"y":0.3657},{"x":0.3321,"y":0.3657},{"x":0.4225,"y":0.3657},{"x":0.5138,"y":0.3657},{"x":0.6043,"y":0.3657},{"x":0.694,"y":0.3657},{"x":0.7799,"y":0.3657},{"x":0.865,"y":0.3657}],[{"x":0.148,"y":0.5133},{"x":0.2408,"y":0.5133},{"x":0.3321,"y":0.5133},{"x":0.4225,"y":0.5133},{"x":0.5138,"y":0.5133},{"x":0.6043,"y":0.5133},{"x":0.694,"y":0.5133},{"x":0.7799,"y":0.5133},{"x":0.8635,"y":0.5133}],[{"x":0.1472,"y":0.6609},{"x":0.2408,"y":0.6609},{"x":0.3321,"y":0.6609},{"x":0.4225,"y":0.6609},{"x":0.5146,"y":0.6609},{"x":0.6043,"y":0.6609},{"x":0.694,"y":0.6609},{"x":0.7799,"y":0.6609},{"x":0.8643,"y":0.6609}],[{"x":0.148,"y":0.8027},{"x":0.2408,"y":0.8027},{"x":0.3321,"y":0.8027},{"x":0.4233,"y":0.8027},{"x":0.51,"y":0.8027},{"x":0.6043,"y":0.8027},{"x":0.694,"y":0.8027},{"x":0.7799,"y":0.8027},{"x":0.8627,"y":0.8027}]];

/** Per-cell centers of the home prize wall (5 shelves x 4 slots), as fractions
 * of the drawn image box. */
export const PRIZE_WALL_SLOTS: { x: number; y: number }[][] = [[{"x":0.24,"y":0.211},{"x":0.4125,"y":0.211},{"x":0.5775,"y":0.211},{"x":0.7425,"y":0.211}],[{"x":0.24,"y":0.338},{"x":0.4125,"y":0.338},{"x":0.5775,"y":0.338},{"x":0.7425,"y":0.338}],[{"x":0.24,"y":0.455},{"x":0.4125,"y":0.455},{"x":0.5775,"y":0.455},{"x":0.7425,"y":0.455}],[{"x":0.24,"y":0.568},{"x":0.4125,"y":0.568},{"x":0.5775,"y":0.568},{"x":0.7425,"y":0.568}],[{"x":0.24,"y":0.692},{"x":0.4125,"y":0.692},{"x":0.5775,"y":0.692},{"x":0.7425,"y":0.692}]];

/** The home room background's visual center line (lamp + wall-gap blend),
 * as a fraction of image width. */
export const ROOM_CENTER_X = 0.5167;
